<?php

namespace Database\Seeders;

use App\Enums\CoreStatus;
use App\Models\Substatus;
use Illuminate\Database\Seeder;

class SubstatusSeeder extends Seeder
{
    public function run(): void
    {
        $substatuses = [
            [
                'name' => 'URGENTE',
                'core_status' => null,
                'is_default' => false,
                'is_global' => true,
                'bg_color' => '#DC2626',
                'text_color' => '#FFFFFF',
                'border_color' => '#B91C1C',
                'is_system' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'TICKET',
                'core_status' => null,
                'is_default' => false,
                'is_global' => true,
                'bg_color' => '#FFE4E6',
                'text_color' => '#9F1239',
                'border_color' => '#FECDD3',
                'is_system' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'POTENTIAL CUSTOMER',
                'core_status' => null,
                'is_default' => false,
                'is_global' => true,
                'bg_color' => '#ECFDF5',
                'text_color' => '#065F46',
                'border_color' => '#A7F3D0',
                'is_system' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'BLOQUEADA',
                'core_status' => CoreStatus::ENTRANTE->value,
                'is_default' => true,
                'is_global' => false,
                'bg_color' => '#FFF7ED',
                'text_color' => '#C2410C',
                'border_color' => '#FFEDD5',
                'is_system' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'OVERDUE',
                'core_status' => null,
                'is_default' => false,
                'is_global' => true,
                'bg_color' => '#FEF2F2',
                'text_color' => '#B91C1C',
                'border_color' => '#FECACA',
                'is_system' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'ALMOST OVERDUE',
                'core_status' => null,
                'is_default' => false,
                'is_global' => true,
                'bg_color' => '#FFFBEB',
                'text_color' => '#B45309',
                'border_color' => '#FDE68A',
                'is_system' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'CAMBIOS CAMILA',
                'core_status' => CoreStatus::ENVIADO_A_CAMILA->value,
                'is_default' => true,
                'is_global' => false,
                'bg_color' => '#FAF5FF',
                'text_color' => '#7E22CE',
                'border_color' => '#E9D5FF',
                'is_system' => false,
                'sort_order' => 7,
            ],
            [
                'name' => 'CAMBIOS CLIENTE',
                'core_status' => CoreStatus::ENVIADO_AL_CLIENTE->value,
                'is_default' => false,
                'is_global' => false,
                'bg_color' => '#F0F9FF',
                'text_color' => '#0369A1',
                'border_color' => '#BAE6FD',
                'is_system' => false,
                'sort_order' => 8,
            ],
            [
                'name' => 'PONER EN ALTA',
                'core_status' => CoreStatus::ENTRANTE->value,
                'is_default' => false,
                'is_global' => false,
                'bg_color' => '#FDF2F8',
                'text_color' => '#BE185D',
                'border_color' => '#FBCFE8',
                'is_system' => false,
                'sort_order' => 9,
            ],
            [
                'name' => 'FALTA APROBACIÓN DE ESTIMADO',
                'core_status' => CoreStatus::ENTRANTE->value,
                'is_default' => false,
                'is_global' => false,
                'bg_color' => '#FFF7ED',
                'text_color' => '#C2410C',
                'border_color' => '#FFEDD5',
                'is_system' => false,
                'sort_order' => 10,
            ],
            [
                'name' => 'NO RESPUESTA',
                'core_status' => CoreStatus::ENVIADO_AL_CLIENTE->value,
                'is_default' => false,
                'is_global' => false,
                'bg_color' => '#F5F5F4',
                'text_color' => '#57534E',
                'border_color' => '#E7E5E4',
                'is_system' => false,
                'sort_order' => 11,
            ],
            [
                'name' => 'PAUSADO',
                'core_status' => CoreStatus::ON_HOLD->value,
                'is_default' => true,
                'is_global' => false,
                'bg_color' => '#F5F5F4',
                'text_color' => '#57534E',
                'border_color' => '#E7E5E4',
                'is_system' => false,
                'sort_order' => 12,
            ],
            [
                'name' => 'ESPERANDO PERMISO',
                'core_status' => CoreStatus::ON_HOLD->value,
                'is_default' => false,
                'is_global' => false,
                'bg_color' => '#FEFCE8',
                'text_color' => '#854D0E',
                'border_color' => '#FEF08A',
                'is_system' => false,
                'sort_order' => 13,
            ],
            [
                'name' => 'AJUSTES DE PRODUCCIÓN',
                'core_status' => CoreStatus::EN_PRODUCCION->value,
                'is_default' => false,
                'is_global' => false,
                'bg_color' => '#FDF2F8',
                'text_color' => '#BE185D',
                'border_color' => '#FBCFE8',
                'is_system' => false,
                'sort_order' => 14,
            ],
            [
                'name' => 'WAITING FOR CLIENT',
                'core_status' => CoreStatus::ENVIADO_AL_CLIENTE->value,
                'is_default' => true,
                'is_global' => false,
                'bg_color' => '#EFF6FF',
                'text_color' => '#1D4ED8',
                'border_color' => '#BFDBFE',
                'is_system' => false,
                'sort_order' => 15,
            ],
            [
                'name' => 'CUSTOMER SERVICE REQUIRED',
                'core_status' => CoreStatus::ON_HOLD->value,
                'is_default' => false,
                'is_global' => false,
                'bg_color' => '#FDF2F8',
                'text_color' => '#BE185D',
                'border_color' => '#FBCFE8',
                'is_system' => false,
                'sort_order' => 16,
            ],
            [
                'name' => 'ENVIADO EN ALTA',
                'core_status' => CoreStatus::EN_PRODUCCION->value,
                'is_default' => true,
                'is_global' => false,
                'bg_color' => '#FDF2F8',
                'text_color' => '#BE185D',
                'border_color' => '#FBCFE8',
                'is_system' => false,
                'sort_order' => 17,
            ],
        ];

        foreach ($substatuses as $data) {
            Substatus::updateOrCreate(['name' => $data['name']], $data);
        }
    }
}
